// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package common

// CommonError defines model for commonError.
type CommonError struct {
	Error struct {
		// Error code
		Code int `json:"code"`

		// Error message
		Message string `json:"message"`

		// Typed reason of error
		Reason string `json:"reason"`
	} `json:"error"`
}

// Авторизационный токен для пользовательской сессии
type PropertyAuthToken = string

// Авторизационный токен для пользовательской сессии
type AuthTokenInHeaders = PropertyAuthToken

// Авторизационный токен для пользовательской сессии
type AuthTokenInQuery = PropertyAuthToken
