openapi: 3.0.0 # https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md
info:
  version: 1.1.1
  title: gateway
  description: API Gateway and API Composition service for Cargo

paths:

  /api/1/auth/check:
    summary: Получение текущих данных по пользователю и авторизационной сессии, если последняя активна
    description: >
      Возвращает данные текущего авторизованного пользователя и данные его авторизационной сессии.
      Если активной авторизационной сессии нет, то вернёт пустые данные.
    parameters:
      - $ref: "./common/schema.yaml#/components/parameters/authTokenInHeaders"
      - $ref: "./common/schema.yaml#/components/parameters/authTokenInQuery"
    get:
      operationId: GetAuthCheck
      responses:
        '200':
          $ref: "./auth/schema.yaml#/components/responses/checkResponseOK"
        '400':
          $ref: "./common/schema.yaml#/components/responses/commonError"
        '401':
          $ref: "./common/schema.yaml#/components/responses/commonError"
        '408':
          $ref: "./common/schema.yaml#/components/responses/commonError"
        '500':
          $ref: "./common/schema.yaml#/components/responses/commonError"

  /api/1/auth/login:
    summary: Авторизация по логину и паролю
    description: >
      Принимает логин (он же username, он же номер телефона или адрес электронной почты).
      В случае успеха вернёт авторизационный токен.
    post:
      operationId: PostAuthLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./auth/schema.yaml#/components/schemas/loginRequestBody"
        required: true
      responses:
        '200':
          $ref: "./auth/schema.yaml#/components/responses/loginResponseOK"
        '400':
          $ref: "./common/schema.yaml#/components/responses/commonError"
        '408':
          $ref: "./common/schema.yaml#/components/responses/commonError"
        '500':
          $ref: "./common/schema.yaml#/components/responses/commonError"
